version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Net/Acrolinx.Net/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Net/Acrolinx.Net.Tests/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
