name: .NET SDK

on:
  push:
    branches: [ BuildMigration ]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  schedule:
    - cron: "30 5 * * *"

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Acrolinx.Net/Acrolinx.Net.sln                                        # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: Acrolinx.Net/Acrolinx.Net.Tests/Acrolinx.Net.Tests.csproj        # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      BUILD_NUMBER: ${{ github.run_number }}
      VERSION: "1.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Nuget restore
      uses: nuget/setup-nuget@v1
    - run: nuget restore $env:Solution_Name

    - name: Build when tag created
      if: startsWith(github.ref,'refs/tags/v')
      shell: powershell
      run: |
        $version = git describe --tags
        msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:Version=$version
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application when tag is not created
      if: false == startsWith(github.ref,'refs/tags/v')
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:Version=$env:VERSION
      env:
        Configuration: ${{ matrix.configuration }}
